In [1]:
import pandas as pd

In [2]:
names_dict = {"names":
        [
            "Tom",
            "Mary",
            "Jeff",
            "Rose",
            "Stephanie",
            "Rodger"
        ]}

In [3]:
print(names_dict["names"])

['Tom', 'Mary', 'Jeff', 'Rose', 'Stephanie', 'Rodger']

In [4]:
df = pd.DataFrame(names_dict)

In [5]:
df.to_csv("./names.csv", index=False)

In [6]:
df_from_csv = pd.read_csv("./names.csv")
print(df_from_csv)

       names
0        Tom
1       Mary
2       Jeff
3       Rose
4  Stephanie
5     Rodger

In [7]:
df.to_json("./names.json")
# print json file
with open("./names.json", "r") as f:
    print(f.read())
df_from_json = pd.read_json("./names.json")
print(df_from_json)

{"names":{"0":"Tom","1":"Mary","2":"Jeff","3":"Rose","4":"Stephanie","5":"Rodger"}}
       names
0        Tom
1       Mary
2       Jeff
3       Rose
4  Stephanie
5     Rodger

In [8]:
df["ages"] = [20, 26, 20, 18, 52, 40]
df

       names  ages
0        Tom    20
1       Mary    26
2       Jeff    20
3       Rose    18
4  Stephanie    52
5     Rodger    40

In [9]:
for idx, row in df.iterrows():
    print(row["names"], row["ages"])

Tom 20
Mary 26
Jeff 20
Rose 18
Stephanie 52
Rodger 40

In [10]:
travel_df = pd.read_csv("./tripadvisor_review.csv")
travel_df.head()

,User ID,Category 1,Category 2,Category 3,Category 4,Category 5,Category 6,Category 7,Category 8,Category 9,Category 10
0,User 1,0.93,1.8,2.29,0.62,0.80,2.42,3.19,2.79,1.82,2.42
1,User 2,1.02,2.2,2.66,0.64,1.42,3.18,3.21,2.63,1.86,2.32
2,User 3,1.22,0.8,0.54,0.53,0.24,1.54,3.18,2.80,1.31,2.50
3,User 4,0.45,1.8,0.29,0.57,0.46,1.52,3.18,2.96,1.57,2.86
4,User 5,0.51,1.2,1.18,0.57,1.54,2.02,3.18,2.78,1.18,2.54

In [11]:
travel_df.describe()

,Category 1,Category 2,Category 3,Category 4,Category 5,Category 6,Category 7,Category 8,Category 9,Category 10
count,980.000000,980.000000,980.000000,980.000000,980.000000,980.000000,980.000000,980.000000,980.000000,980.000000
mean,0.893194,1.352612,1.013306,0.532500,0.939735,1.842898,3.180939,2.835061,1.569439,2.799224
std,0.326912,0.478280,0.788607,0.279731,0.437430,0.539538,0.007824,0.137505,0.364629,0.321380
min,0.340000,0.000000,0.130000,0.150000,0.060000,0.140000,3.160000,2.420000,0.740000,2.140000
25%,0.670000,1.080000,0.270000,0.410000,0.640000,1.460000,3.180000,2.740000,1.310000,2.540000
50%,0.830000,1.280000,0.820000,0.500000,0.900000,1.800000,3.180000,2.820000,1.540000,2.780000
75%,1.020000,1.560000,1.572500,0.580000,1.200000,2.200000,3.180000,2.910000,1.760000,3.040000
max,3.220000,3.640000,3.620000,3.440000,3.300000,3.760000,3.210000,3.390000,3.170000,3.660000

In [12]:
travel_df[(travel_df["Category 6"] < 2) | (travel_df["Category 2"] > 2)]["Category 6"].count()

np.int64(650)

In [53]:
bike_df = pd.read_csv("./bike_sharing_hour.csv")

In [54]:
bike_df = bike_df.rename(columns={"instant": "instance"})

In [18]:
bike_df.head()

,instance,dteday,season,yr,mnth,hr,holiday,weekday,workingday,weathersit,temp,atemp,hum,windspeed,casual,registered,cnt
0,1,2011-01-01,1,0,1,0,0,6,0,1,0.24,0.2879,0.81,0.0,3,13,16
1,2,2011-01-01,1,0,1,1,0,6,0,1,0.22,0.2727,0.80,0.0,8,32,40
2,3,2011-01-01,1,0,1,2,0,6,0,1,0.22,0.2727,0.80,0.0,5,27,32
3,4,2011-01-01,1,0,1,3,0,6,0,1,0.24,0.2879,0.75,0.0,3,10,13
4,5,2011-01-01,1,0,1,4,0,6,0,1,0.24,0.2879,0.75,0.0,0,1,1

In [20]:
bike_df.describe()

,instance,season,yr,mnth,hr,holiday,weekday,workingday,weathersit,temp,atemp,hum,windspeed,casual,registered,cnt
count,17379.0000,17379.000000,17379.000000,17379.000000,17379.000000,17379.000000,17379.000000,17379.000000,17379.000000,17379.000000,17379.000000,17379.000000,17379.000000,17379.000000,17379.000000,17379.000000
mean,8690.0000,2.501640,0.502561,6.537775,11.546752,0.028770,3.003683,0.682721,1.425283,0.496987,0.475775,0.627229,0.190098,35.676218,153.786869,189.463088
std,5017.0295,1.106918,0.500008,3.438776,6.914405,0.167165,2.005771,0.465431,0.639357,0.192556,0.171850,0.192930,0.122340,49.305030,151.357286,181.387599
min,1.0000,1.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.020000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000
25%,4345.5000,2.000000,0.000000,4.000000,6.000000,0.000000,1.000000,0.000000,1.000000,0.340000,0.333300,0.480000,0.104500,4.000000,34.000000,40.000000
50%,8690.0000,3.000000,1.000000,7.000000,12.000000,0.000000,3.000000,1.000000,1.000000,0.500000,0.484800,0.630000,0.194000,17.000000,115.000000,142.000000
75%,13034.5000,3.000000,1.000000,10.000000,18.000000,0.000000,5.000000,1.000000,2.000000,0.660000,0.621200,0.780000,0.253700,48.000000,220.000000,281.000000
max,17379.0000,4.000000,1.000000,12.000000,23.000000,1.000000,6.000000,1.000000,4.000000,1.000000,1.000000,1.000000,0.850700,367.000000,886.000000,977.000000

In [23]:
bike_df[(bike_df["workingday"] == 0) & (bike_df["holiday"] == 0)]

,instance,dteday,season,yr,mnth,hr,holiday,weekday,workingday,weathersit,temp,atemp,hum,windspeed,casual,registered,cnt
0,1,2011-01-01,1,0,1,0,0,6,0,1,0.24,0.2879,0.81,0.0000,3,13,16
1,2,2011-01-01,1,0,1,1,0,6,0,1,0.22,0.2727,0.80,0.0000,8,32,40
2,3,2011-01-01,1,0,1,2,0,6,0,1,0.22,0.2727,0.80,0.0000,5,27,32
3,4,2011-01-01,1,0,1,3,0,6,0,1,0.24,0.2879,0.75,0.0000,3,10,13
4,5,2011-01-01,1,0,1,4,0,6,0,1,0.24,0.2879,0.75,0.0000,0,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17350,17351,2012-12-30,1,1,12,19,0,0,0,1,0.34,0.3636,0.61,0.0000,16,86,102
17351,17352,2012-12-30,1,1,12,20,0,0,0,1,0.22,0.1970,0.47,0.3284,9,63,72
17352,17353,2012-12-30,1,1,12,21,0,0,0,1,0.20,0.2121,0.51,0.1642,5,42,47
17353,17354,2012-12-30,1,1,12,22,0,0,0,1,0.20,0.1970,0.55,0.1940,6,30,36
17354,17355,2012-12-30,1,1,12,23,0,0,0,1,0.20,0.1970,0.51,0.2239,10,39,49

In [24]:
bike_df.sort_values(by="hr")

,instance,dteday,season,yr,mnth,hr,holiday,weekday,workingday,weathersit,temp,atemp,hum,windspeed,casual,registered,cnt
0,1,2011-01-01,1,0,1,0,0,6,0,1,0.24,0.2879,0.81,0.0000,3,13,16
5653,5654,2011-08-29,3,0,8,0,0,1,1,1,0.62,0.5909,0.73,0.1045,13,21,34
5618,5619,2011-08-27,3,0,8,0,0,6,0,1,0.70,0.6667,0.84,0.1045,33,112,145
5594,5595,2011-08-26,3,0,8,0,0,5,1,1,0.62,0.5758,0.83,0.1343,9,42,51
5570,5571,2011-08-25,3,0,8,0,0,4,1,1,0.68,0.6364,0.74,0.2985,11,41,52
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7568,7569,2011-11-16,4,0,11,23,0,3,1,3,0.42,0.4242,0.88,0.1343,3,28,31
7544,7545,2011-11-15,4,0,11,23,0,2,1,2,0.46,0.4545,0.94,0.1045,14,66,80
7520,7521,2011-11-14,4,0,11,23,0,1,1,1,0.56,0.5303,0.64,0.2985,13,48,61
7832,7833,2011-11-27,4,0,11,23,0,0,0,1,0.48,0.4697,0.72,0.2537,5,27,32
17378,17379,2012-12-31,1,1,12,23,0,1,1,1,0.26,0.2727,0.65,0.1343,12,37,49

In [ ]:
bike_df.sort_values(["holiday", "dteday", "hr"], ascending=[False, True, True])

,instance,dteday,season,yr,mnth,hr,holiday,weekday,workingday,weathersit,temp,atemp,hum,windspeed,casual,registered,cnt
372,373,2011-01-17,1,0,1,0,1,1,0,2,0.20,0.1970,0.47,0.2239,1,16,17
373,374,2011-01-17,1,0,1,1,1,1,0,2,0.20,0.1970,0.44,0.1940,1,15,16
374,375,2011-01-17,1,0,1,2,1,1,0,2,0.18,0.1667,0.43,0.2537,0,8,8
375,376,2011-01-17,1,0,1,3,1,1,0,2,0.18,0.1818,0.43,0.1940,0,2,2
376,377,2011-01-17,1,0,1,4,1,1,0,2,0.18,0.1970,0.43,0.1343,1,2,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17374,17375,2012-12-31,1,1,12,19,0,1,1,2,0.26,0.2576,0.60,0.1642,11,108,119
17375,17376,2012-12-31,1,1,12,20,0,1,1,2,0.26,0.2576,0.60,0.1642,8,81,89
17376,17377,2012-12-31,1,1,12,21,0,1,1,1,0.26,0.2576,0.60,0.1642,7,83,90
17377,17378,2012-12-31,1,1,12,22,0,1,1,1,0.26,0.2727,0.56,0.1343,13,48,61
17378,17379,2012-12-31,1,1,12,23,0,1,1,1,0.26,0.2727,0.65,0.1343,12,37,49

In [36]:
bike_df.drop(columns=["instance"])

,dteday,season,yr,mnth,hr,holiday,weekday,workingday,weathersit,temp,atemp,hum,windspeed,casual,registered,cnt
0,2011-01-01,1,0,1,0,0,6,0,1,0.24,0.2879,0.81,0.0000,3,13,16
1,2011-01-01,1,0,1,1,0,6,0,1,0.22,0.2727,0.80,0.0000,8,32,40
2,2011-01-01,1,0,1,2,0,6,0,1,0.22,0.2727,0.80,0.0000,5,27,32
3,2011-01-01,1,0,1,3,0,6,0,1,0.24,0.2879,0.75,0.0000,3,10,13
4,2011-01-01,1,0,1,4,0,6,0,1,0.24,0.2879,0.75,0.0000,0,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17374,2012-12-31,1,1,12,19,0,1,1,2,0.26,0.2576,0.60,0.1642,11,108,119
17375,2012-12-31,1,1,12,20,0,1,1,2,0.26,0.2576,0.60,0.1642,8,81,89
17376,2012-12-31,1,1,12,21,0,1,1,1,0.26,0.2576,0.60,0.1642,7,83,90
17377,2012-12-31,1,1,12,22,0,1,1,1,0.26,0.2727,0.56,0.1343,13,48,61
17378,2012-12-31,1,1,12,23,0,1,1,1,0.26,0.2727,0.65,0.1343,12,37,49

In [ ]:
from datetime import date
my_date = "2011-01-01"
date(*[int(x) for x in my_date.split("-")])

2011-01-01

In [ ]:
pd.to_datetime(bike_df["dteday"])

0       2011-01-01
1       2011-01-01
2       2011-01-01
3       2011-01-01
4       2011-01-01
           ...
17374   2012-12-31
17375   2012-12-31
17376   2012-12-31
17377   2012-12-31
17378   2012-12-31
Name: dteday, Length: 17379, dtype: datetime64[us]

In [51]:
bike_df[(bike_df["hr"] <= 10) & (bike_df["hr"] >= 7)]

,instance,dteday,season,yr,mnth,hr,holiday,weekday,workingday,weathersit,temp,atemp,hum,windspeed,casual,registered,cnt
7,8,2011-01-01,1,0,1,7,0,6,0,1,0.20,0.2576,0.86,0.0000,1,2,3
8,9,2011-01-01,1,0,1,8,0,6,0,1,0.24,0.2879,0.75,0.0000,1,7,8
9,10,2011-01-01,1,0,1,9,0,6,0,1,0.32,0.3485,0.76,0.0000,8,6,14
10,11,2011-01-01,1,0,1,10,0,6,0,1,0.38,0.3939,0.76,0.2537,12,24,36
30,31,2011-01-02,1,0,1,7,0,0,0,2,0.40,0.4091,0.76,0.1940,0,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17341,17342,2012-12-30,1,1,12,10,0,0,0,1,0.26,0.2121,0.41,0.5821,31,91,122
17362,17363,2012-12-31,1,1,12,7,0,1,1,1,0.16,0.1818,0.64,0.1343,2,83,85
17363,17364,2012-12-31,1,1,12,8,0,1,1,1,0.14,0.1515,0.69,0.1343,9,187,196
17364,17365,2012-12-31,1,1,12,9,0,1,1,2,0.18,0.2121,0.64,0.1045,13,144,157
17365,17366,2012-12-31,1,1,12,10,0,1,1,2,0.20,0.2121,0.69,0.1343,33,87,120

In [55]:
bike_df[bike_df["dteday"].str.endswith("-01")]

,instance,dteday,season,yr,mnth,hr,holiday,weekday,workingday,weathersit,temp,atemp,hum,windspeed,casual,registered,cnt
0,1,2011-01-01,1,0,1,0,0,6,0,1,0.24,0.2879,0.81,0.0,3,13,16
1,2,2011-01-01,1,0,1,1,0,6,0,1,0.22,0.2727,0.80,0.0,8,32,40
2,3,2011-01-01,1,0,1,2,0,6,0,1,0.22,0.2727,0.80,0.0,5,27,32
3,4,2011-01-01,1,0,1,3,0,6,0,1,0.24,0.2879,0.75,0.0,3,10,13
4,5,2011-01-01,1,0,1,4,0,6,0,1,0.24,0.2879,0.75,0.0,0,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16656,16657,2012-12-01,4,1,12,19,0,6,0,2,0.32,0.3485,0.81,0.0,30,219,249
16657,16658,2012-12-01,4,1,12,20,0,6,0,1,0.32,0.3485,0.81,0.0,28,170,198
16658,16659,2012-12-01,4,1,12,21,0,6,0,2,0.30,0.3333,0.87,0.0,23,135,158
16659,16660,2012-12-01,4,1,12,22,0,6,0,2,0.30,0.3333,0.87,0.0,17,130,147
16660,16661,2012-12-01,4,1,12,23,0,6,0,2,0.32,0.3485,0.81,0.0,10,116,126

In [59]:
bike_df["cnt"].groupby(bike_df["hr"]).sum()

hr
0      39130
1      24164
2      16352
3       8174
4       4428
5      14261
6      55132
7     154171
8     261001
9     159438
10    126257
11    151320
12    184414
13    184919
14    175652
15    183149
16    227748
17    336860
18    309772
19    226789
20    164550
21    125445
22     95612
23     63941
Name: cnt, dtype: int64